export const BACKEND_AUTHORIZATION_MATRIX = {
  adminOnly: [
    "core.saveSystemSettings",
    "core.userManagement",
    "core.createEmployee",
    "core.updateEmployee",
    "core.deleteEmployee",
    "core.saveTagSettings",
    "core.deleteArea",
    "core.deleteProject",
    "accessControl.model",
    "workflow.delete",
  ],
  coordinatorOrAdmin: [
    "core.createArea",
    "core.updateArea",
    "core.createProject",
    "core.updateProject",
  ],
  supervisorOrAdmin: [
    "core.savePhaseAssignments",
    "workflow.save",
  ],
  authenticated: [
    "core.persistenceStatus",
    "core.systemSettings",
    "core.areas",
    "core.projects",
    "core.blinds",
    "core.dashboardSummary",
    "core.employees",
    "core.phaseAssignments",
    "core.phaseGatePreview",
    "core.approvalProfiles",
    "core.approvalCenter",
    "core.certificateLock",
    "core.pendingApprovals",
    "core.approveRequest",
    "core.torqueRecords",
    "core.certificates",
    "core.issueCertificate",
    "core.tagSettings",
    "core.notifications",
    "core.updateNotification",
    "core.auditTrail",
    "core.recordTagPrint",
    "core.reportCenter",
    "core.recordReportExport",
    "core.createBlind",
    "core.blindDetail",
    "core.moveBlindPhase",
    "workflow.list",
    "workflow.get",
  ],
  publicAllowed: [
    "system.health",
    "core.login",
    "core.sessionBinding",
    "core.registerEmployeeCredential",
    "core.passwordLogin",
    "core.requestPasswordReset",
    "auth.me",
    "auth.logout",
  ],
} as const;

export type BackendAuthorizationMatrix = typeof BACKEND_AUTHORIZATION_MATRIX;
